name: (algolia-synonyms) Build and deploy to Firebase
on:
  push:
    branches:
      - master
    paths:
      - 'algolia-synonyms/**'
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to run the workflow on"
        default: "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: algolia-synonyms

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install

      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-hosting-deploy
        with:
          firebaseToolsVersion: "12.9.1"
          firebaseServiceAccount: "${{ secrets.MD_EXTS_FIREBASE_SA }}"
          projectId: frontend-extensions
          channelId: live
          target: emporix-algolia-synonyms
