name: PR checks (deploy preview in firebase etc.)

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
    paths:
      - 'algolia-synonyms/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: algolia-synonyms

    strategy:
      matrix:
        node: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - run: yarn install

      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-hosting-preview
        with:
          firebaseToolsVersion: "12.9.1"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.MD_EXTS_FIREBASE_SA }}"
          expires: 5d
          projectId: frontend-extensions
          target: emporix-algolia-synonyms
